=== SamTay/magento-modules/EntityMap/etc/entity_decode.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--/*
 * @package     BlueAcorn\EntityMap
 * @version     1.0.0
 * @author      Sam Tay @ Blue Acorn, Inc. <code@blueacorn.com>
 * @copyright   Copyright Â© 2016 Blue Acorn, Inc.
 */-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="config">
        <xs:complexType>
            <xs:sequence minOccurs="1" maxOccurs="unbounded">
                <xs:element name="entity" type="entityDeclaration" minOccurs="1" maxOccurs="unbounded">
                    <xs:unique name="uniqueKeyFrom">
                        <xs:annotation>
                            <xs:documentation>
                                Key "from" attribute must be unique
                            </xs:documentation>
                        </xs:annotation>
                        <xs:selector xpath="key_map"/>
                        <xs:field xpath="@from"/>
                    </xs:unique>
                    <xs:unique name="uniqueAttributeCode">
                        <xs:annotation>
                            <xs:documentation>
                                Attribute code must be unique
                            </xs:documentation>
                        </xs:annotation>
                        <xs:selector xpath="attribute_map"/>
                        <xs:field xpath="@code"/>
                    </xs:unique>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
        <xs:unique name="uniqueEntityName">
            <xs:annotation>
                <xs:documentation>
                    Import entity name must be unique.
                </xs:documentation>
            </xs:annotation>
            <xs:selector xpath="entity"/>
            <xs:field xpath="@name"/>
        </xs:unique>
    </xs:element>

    <xs:complexType name="entityDeclaration">
        <xs:annotation>
            <xs:documentation>
                Import entity declaration.
            </xs:documentation>
        </xs:annotation>
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:element name="key_map" type="keyMapDeclaration" minOccurs="0" maxOccurs="unbounded" />
            <xs:element name="aggregate" type="aggregateDeclaration" minOccurs="0" maxOccurs="unbounded">
                <xs:unique name="uniqueKeyId">
                    <xs:annotation>
                        <xs:documentation>
                            Key "id" attribute must be unique
                        </xs:documentation>
                    </xs:annotation>
                    <xs:selector xpath="key"/>
                    <xs:field xpath="@id"/>
                </xs:unique>
            </xs:element>
            <xs:element name="attribute_map" type="attributeMapperDeclaration" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required" />
    </xs:complexType>

    <xs:complexType name="keyMapDeclaration">
        <xs:attribute name="from" type="xs:string" use="required" />
        <xs:attribute name="to" type="attributeCode" use="required" />
    </xs:complexType>

    <xs:complexType name="aggregateDeclaration">
        <xs:sequence minOccurs="1" maxOccurs="unbounded">
            <xs:element name="key" type="keyDeclaration" minOccurs="1" maxOccurs="unbounded" />
        </xs:sequence>
        <xs:attribute name="id" type="attributeCode" use="required" />
    </xs:complexType>

    <xs:complexType name="keyDeclaration">
        <xs:attribute name="id" type="xs:string" use="required" />
    </xs:complexType>

    <xs:complexType name="attributeMapperDeclaration">
        <xs:attribute name="code" type="attributeCode" use="required" />
        <xs:attribute name="mapper" type="modelName" use="required" />
    </xs:complexType>

    <xs:simpleType name="attributeCode">
        <xs:annotation>
            <xs:documentation>
                Attribute code can contain only alphanumeric characters, up to length 30
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-zA-Z0-9_]+" />
            <xs:maxLength value="30" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="modelName">
        <xs:annotation>
            <xs:documentation>
                Model name can contain only [A-Za-z_\\\\].
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Za-z_\\\\]+" />
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== SamTay/magento-modules/docs/examples/ProductIntegration/etc/entity_decode.xml
<?xml version="1.0"?>
<!--/*
 * @package     BlueAcorn\ProductIntegration
 * @version     1.0.0
 * @author      Sam Tay @ Blue Acorn, Inc. <code@blueacorn.com>
 * @copyright   Copyright Â© 2016 Blue Acorn, Inc.
 */-->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:blueacorn:framework-entity-map:etc/entity_decode.xsd">
    <entity name="catalog_product">
        <key_map from="somethingCamelCased" to="something_snake_cased" />
        <key_map from="anotherExample" to="another_example" />
        <key_map from="spColor" to="color" />
        <aggregate id="confidence_builder">
            <key id="free_shipping_all_orders" />
            <key id="money_back_guarantee" />
        </aggregate>
        <attribute_map code="color" mapper="BlueAcorn\ProductIntegration\Model\Mapper\Attribute\Color" />
        <attribute_map code="confidence_builder" mapper="BlueAcorn\ProductIntegration\Model\Mapper\Attribute\ConfidenceBuilder" />
    </entity>
</config>
